// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } 
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcRKjTMUZVkETAa59yGjUYwRubeugFBJw',
    appId: '1:1031419504649:web:0d0c910d7e65698b1af0d8',
    messagingSenderId: '1031419504649',
    projectId: 'radiusappcso',
    authDomain: 'radiusappcso.firebaseapp.com',
    storageBucket: 'radiusappcso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRKjTMUZVkETAa59yGjUYwRubeugFBJw',
    appId: '1:1031419504649:android:0d0c910d7e65698b1af0d8',
    messagingSenderId: '1031419504649',
    projectId: 'radiusappcso',
    storageBucket: 'radiusappcso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRKjTMUZVkETAa59yGjUYwRubeugFBJw',
    appId: '1:1031419504649:ios:0d0c910d7e65698b1af0d8',
    messagingSenderId: '1031419504649',
    projectId: 'radiusappcso',
    storageBucket: 'radiusappcso.firebasestorage.app',
    iosBundleId: 'com.codeshowoff.radius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcRKjTMUZVkETAa59yGjUYwRubeugFBJw',
    appId: '1:1031419504649:ios:0d0c910d7e65698b1af0d8',
    messagingSenderId: '1031419504649',
    projectId: 'radiusappcso',
    storageBucket: 'radiusappcso.firebasestorage.app',
    iosBundleId: 'com.codeshowoff.radius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcRKjTMUZVkETAa59yGjUYwRubeugFBJw',
    appId: '1:1031419504649:web:0d0c910d7e65698b1af0d8',
    messagingSenderId: '1031419504649',
    projectId: 'radiusappcso',
    authDomain: 'radiusappcso.firebaseapp.com',
    storageBucket: 'radiusappcso.firebasestorage.app',
  );
}