// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } 
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8feyW4YatnwiJfkln2XCdobAtHRuS6Z0',
    appId: '1:486551872927:web:756fd15799f804eedcc9aa',
    messagingSenderId: '486551872927',
    projectId: 'radiusapp-ecfcd',
    authDomain: 'radiusapp-ecfcd.firebaseapp.com',
    storageBucket: 'radiusapp-ecfcd.firebasestorage.app',
    measurementId: 'G-19723T3N8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDQJIooySxhx96nAE_PjwRKpVZk-ddDU',
    appId: '1:486551872927:android:9d8bfaf52a369100dcc9aa',
    messagingSenderId: '486551872927',
    projectId: 'radiusapp-ecfcd',
    storageBucket: 'radiusapp-ecfcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvShQy75UYraL7T8gbMd9ckS5OamX5qs',
    appId: '1:486551872927:ios:a5895d5ac8a3bf15dcc9aa',
    messagingSenderId: '486551872927',
    projectId: 'radiusapp-ecfcd',
    storageBucket: 'radiusapp-ecfcd.firebasestorage.app',
    androidClientId: '486551872927-4ct5jov5nfmdhpsh6a08c3vmbch3cqqt.apps.googleusercontent.com',
    iosClientId: '486551872927-sf24d31nm53illbf2ijircm7a17s4dsj.apps.googleusercontent.com',
    iosBundleId: 'com.codeshowoff.radius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvShQy75UYraL7T8gbMd9ckS5OamX5qs',
    appId: '1:486551872927:ios:a5895d5ac8a3bf15dcc9aa',
    messagingSenderId: '486551872927',
    projectId: 'radiusapp-ecfcd',
    storageBucket: 'radiusapp-ecfcd.firebasestorage.app',
    androidClientId: '486551872927-4ct5jov5nfmdhpsh6a08c3vmbch3cqqt.apps.googleusercontent.com',
    iosClientId: '486551872927-sf24d31nm53illbf2ijircm7a17s4dsj.apps.googleusercontent.com',
    iosBundleId: 'com.codeshowoff.radius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8feyW4YatnwiJfkln2XCdobAtHRuS6Z0',
    appId: '1:486551872927:web:777b028085c1bbc1dcc9aa',
    messagingSenderId: '486551872927',
    projectId: 'radiusapp-ecfcd',
    authDomain: 'radiusapp-ecfcd.firebaseapp.com',
    storageBucket: 'radiusapp-ecfcd.firebasestorage.app',
    measurementId: 'G-BXJVLMGE76',
  );

}